"""
Platform definitions for HandyOsint.
"""

PLATFORM_CATEGORIES = {
    "social_media": {
        "name": "Social Media Platforms",
        "color": "cyan",
        "risk_weight": 0.8,
        "platforms": ["twitter", "instagram", "tiktok", "reddit", "snapchat", "threads"],
    },
    "developer": {
        "name": "Developer Communities",
        "color": "white",
        "risk_weight": 0.6,
        "platforms": ["github", "gitlab", "stackoverflow", "dev_to", "codepen"],
    },
    "professional": {
        "name": "Professional Networks",
        "color": "blue",
        "risk_weight": 0.5,
        "platforms": ["linkedin"],
    },
    "content": {
        "name": "Content Platforms",
        "color": "magenta",
        "risk_weight": 0.7,
        "platforms": ["youtube", "twitch", "medium", "pinterest", "spotify"],
    },
    "messaging": {
        "name": "Messaging Platforms",
        "color": "green",
        "risk_weight": 0.9,
        "platforms": ["telegram"],
    },
    "monetization": {
        "name": "Monetization Platforms",
        "color": "yellow",
        "risk_weight": 0.4,
        "platforms": ["patreon"],
    },
    "decentralized": {
        "name": "Decentralized Networks",
        "color": "magenta",
        "risk_weight": 0.85,
        "platforms": ["mastodon", "bluesky"],
    },
}

PLATFORM_INFO = {
    "twitter": {
        "name": "Twitter/X",
        "icon": "𝕏",
        "category": "social_media",
        "url_template": "https://twitter.com/{username}",
        "color": "blue",
        "audience": "public",
        "activity_type": "tweets",
        "risk_score": 0.85,
        "data_exposure": ["posts", "followers", "engagement", "location"],
    },
    "instagram": {
        "name": "Instagram",
        "icon": "📷",
        "category": "social_media",
        "url_template": "https://instagram.com/{username}",
        "color": "magenta",
        "audience": "semi-public",
        "activity_type": "photos",
        "risk_score": 0.75,
        "data_exposure": ["photos", "stories", "followers", "bio"],
    },
    "tiktok": {
        "name": "TikTok",
        "icon": "🎵",
        "category": "social_media",
        "url_template": "https://tiktok.com/@{username}",
        "color": "cyan",
        "audience": "public",
        "activity_type": "videos",
        "risk_score": 0.80,
        "data_exposure": ["videos", "comments", "likes", "engagement"],
    },
    "reddit": {
        "name": "Reddit",
        "icon": "🔴",
        "category": "social_media",
        "url_template": "https://reddit.com/user/{username}",
        "color": "red",
        "audience": "public",
        "activity_type": "posts",
        "risk_score": 0.70,
        "data_exposure": ["posts", "comments", "history"],
    },
    "linkedin": {
        "name": "LinkedIn",
        "icon": "💼",
        "category": "professional",
        "url_template": "https://linkedin.com/in/{username}",
        "color": "blue",
        "audience": "semi-public",
        "activity_type": "work_history",
        "risk_score": 0.55,
        "data_exposure": ["employment", "education", "connections"],
    },
    "github": {
        "name": "GitHub",
        "icon": "🐙",
        "category": "developer",
        "url_template": "https://github.com/{username}",
        "color": "white",
        "audience": "public",
        "activity_type": "code",
        "risk_score": 0.60,
        "data_exposure": ["repositories", "code", "contribution_history"],
    },
    "gitlab": {
        "name": "GitLab",
        "icon": "🦊",
        "category": "developer",
        "url_template": "https://gitlab.com/{username}",
        "color": "yellow",
        "audience": "configurable",
        "activity_type": "code",
        "risk_score": 0.55,
        "data_exposure": ["repositories", "code", "profile"],
    },
    "stackoverflow": {
        "name": "Stack Overflow",
        "icon": "📚",
        "category": "developer",
        "url_template": "https://stackoverflow.com/users/{username}",
        "color": "yellow",
        "audience": "public",
        "activity_type": "answers",
        "risk_score": 0.45,
        "data_exposure": ["expertise", "Q&A history"],
    },
    "youtube": {
        "name": "YouTube",
        "icon": "▶️",
        "category": "content",
        "url_template": "https://youtube.com/@{username}",
        "color": "red",
        "audience": "public",
        "activity_type": "videos",
        "risk_score": 0.65,
        "data_exposure": ["videos", "subscribers", "engagement"],
    },
    "twitch": {
        "name": "Twitch",
        "icon": "📺",
        "category": "content",
        "url_template": "https://twitch.tv/{username}",
        "color": "magenta",
        "audience": "public",
        "activity_type": "streams",
        "risk_score": 0.70,
        "data_exposure": ["streams", "followers", "chat_history"],
    },
    "medium": {
        "name": "Medium",
        "icon": "📝",
        "category": "content",
        "url_template": "https://medium.com/@{username}",
        "color": "white",
        "audience": "public",
        "activity_type": "articles",
        "risk_score": 0.50,
        "data_exposure": ["articles", "interests", "followers"],
    },
    "patreon": {
        "name": "Patreon",
        "icon": "❤️",
        "category": "monetization",
        "url_template": "https://patreon.com/{username}",
        "color": "red",
        "audience": "public",
        "activity_type": "patronage",
        "risk_score": 0.40,
        "data_exposure": ["supporters", "content"],
    },
    "telegram": {
        "name": "Telegram",
        "icon": "✈️",
        "category": "messaging",
        "url_template": "https://t.me/{username}",
        "color": "cyan",
        "audience": "public",
        "activity_type": "messaging",
        "risk_score": 0.90,
        "data_exposure": ["contact", "channel_access", "groups"],
    },
    "snapchat": {
        "name": "Snapchat",
        "icon": "👻",
        "category": "social_media",
        "url_template": "https://snapchat.com/add/{username}",
        "color": "yellow",
        "audience": "semi-public",
        "activity_type": "stories",
        "risk_score": 0.72,
        "data_exposure": ["stories", "friends"],
    },
    "mastodon": {
        "name": "Mastodon",
        "icon": "🐘",
        "category": "decentralized",
        "url_template": "https://mastodon.social/@{username}",
        "color": "blue",
        "audience": "configurable",
        "activity_type": "toots",
        "risk_score": 0.65,
        "data_exposure": ["posts", "followers"],
    },
    "bluesky": {
        "name": "Bluesky",
        "icon": "🦋",
        "category": "decentralized",
        "url_template": "https://bsky.app/profile/{username}",
        "color": "cyan",
        "audience": "public",
        "activity_type": "posts",
        "risk_score": 0.70,
        "data_exposure": ["posts", "followers", "engagement"],
    },
    "threads": {
        "name": "Threads",
        "icon": "🧵",
        "category": "social_media",
        "url_template": "https://threads.net/@{username}",
        "color": "black",
        "audience": "public",
        "activity_type": "posts",
        "risk_score": 0.78,
        "data_exposure": ["posts", "followers", "engagement"],
    },
    "dev_to": {
        "name": "Dev.to",
        "icon": "💻",
        "category": "developer",
        "url_template": "https://dev.to/{username}",
        "color": "white",
        "audience": "public",
        "activity_type": "articles",
        "risk_score": 0.48,
        "data_exposure": ["articles", "expertise"],
    },
    "codepen": {
        "name": "CodePen",
        "icon": "🎨",
        "category": "developer",
        "url_template": "https://codepen.io/{username}",
        "color": "white",
        "audience": "public",
        "activity_type": "projects",
        "risk_score": 0.50,
        "data_exposure": ["projects", "code"],
    },
    "pinterest": {
        "name": "Pinterest",
        "icon": "📌",
        "category": "content",
        "url_template": "https://pinterest.com/{username}",
        "color": "red",
        "audience": "public",
        "activity_type": "pins",
        "risk_score": 0.55,
        "data_exposure": ["pins", "interests", "boards"],
    },
    "spotify": {
        "name": "Spotify",
        "icon": "🎧",
        "category": "content",
        "url_template": "https://open.spotify.com/user/{username}",
        "color": "green",
        "audience": "configurable",
        "activity_type": "playlists",
        "risk_score": 0.45,
        "data_exposure": ["playlists", "music_preferences"],
    },
}
